playerPresence:
  target: "localhost:9000"
  plaintext: true
  timeoutMillis: 2000

messages:
  serviceUnavailable: "Login service unavailable"
  alreadyOnline: "You are already online."
  invalidRequest: "Invalid login request."
  genericError: "Unable to create player session."

